services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=runnerz'
      - 'POSTGRES_PASSWORD=MariamDatabase77'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
